global:
  manetu:
    imagePullSecrets:
      - name: gitlab-regcred # the cred derived from gitlab ci
    platformoperator:
      existingSecret: platform-operator-secret
mcp-iam-service:
  platformoperator:
    existingSecret: platform-operator-secret