include:
  - project: manetu/tools/ci-tools
    ref: v3.0.0
    file: /templates/docker.yml

.citools_variables:
  variables:
    MANETU_RELEASE_STREAM: "2.2.0"
    KANIKO_EXECUTOR_ARGS: --build-arg GITLAB_TOKEN_VALUE=$CI_JOB_TOKEN

# Approve
approve_release:
  extends: .approve_release
  when: on_success

github_mirror:
  image: registry.gitlab.com/manetu/tools/unified-builder:v3.0
  stage: release
  extends:
    - .only_release_job
  except:
    - tags
  dependencies:
    - approve_release
  variables:
    GIT_STRATEGY: fetch # need git repo for pushing upstream
  script:
    - echo "machine $GIT_MIRROR_HOST login $GIT_MIRROR_USERNAME password $GIT_MIRROR_PASSWORD" > $HOME/.netrc && chmod 600 $HOME/.netrc
    - git push $GIT_MIRROR_REPO HEAD:$CI_COMMIT_BRANCH

git_release:
  extends: .git_release

git_release_verify:
  extends: .git_release_verify
