apiVersion: v1
kind: Secret
metadata:
  name: platform-operator-secret
  namespace: manetu-platform
type: Opaque
stringData:
  SERVICE_PLATFORMOPERATOR_CREDENTIALS_TYPE: x509
  SERVICE_PLATFORMOPERATOR_CREDENTIALS_DATA: |
    -----BEGIN CERTIFICATE-----
    MIIBfTCCASOgAwIBAgIUBECO8bCVruvWh8QXA25O1g5PeOEwCgYIKoZIzj0EAwIw
    FDESMBAGA1UECgwJbWFuZXR1LmlvMB4XDTI0MTIxMDE2NTIyOVoXDTM0MTIwODE2
    NTIyOVowFDESMBAGA1UECgwJbWFuZXR1LmlvMFkwEwYHKoZIzj0CAQYIKoZIzj0D
    AQcDQgAE5Aamr37PUJ2+YE+Hp+xXAzRkSf5L7VzMwLoBXr1NeK7j9VSNfCswlq2U
    vEsmvqVsIIjrVLXZD9IdPymcgIZEdqNTMFEwHQYDVR0OBBYEFPtyaoIP60xIlB4/
    AVSZ/N+Z6tKTMB8GA1UdIwQYMBaAFPtyaoIP60xIlB4/AVSZ/N+Z6tKTMA8GA1Ud
    EwEB/wQFMAMBAf8wCgYIKoZIzj0EAwIDSAAwRQIgBsRwbwJyFF74N2PVzc7R6nPE
    7Ot8gGj6Vg5dJbFseioCIQD2m1DYj2F3UAf9FV9l4EXz1qWn7yLpso9NRSQM4Iub
    fw==
    -----END CERTIFICATE-----
---
apiVersion: v1
kind: Secret
metadata:
  name: platform-operator-credentials
  namespace: manetu-platform
type: Opaque
stringData:
  cert.pem: |
    -----BEGIN CERTIFICATE-----
    MIIBfTCCASOgAwIBAgIUBECO8bCVruvWh8QXA25O1g5PeOEwCgYIKoZIzj0EAwIw
    FDESMBAGA1UECgwJbWFuZXR1LmlvMB4XDTI0MTIxMDE2NTIyOVoXDTM0MTIwODE2
    NTIyOVowFDESMBAGA1UECgwJbWFuZXR1LmlvMFkwEwYHKoZIzj0CAQYIKoZIzj0D
    AQcDQgAE5Aamr37PUJ2+YE+Hp+xXAzRkSf5L7VzMwLoBXr1NeK7j9VSNfCswlq2U
    vEsmvqVsIIjrVLXZD9IdPymcgIZEdqNTMFEwHQYDVR0OBBYEFPtyaoIP60xIlB4/
    AVSZ/N+Z6tKTMB8GA1UdIwQYMBaAFPtyaoIP60xIlB4/AVSZ/N+Z6tKTMA8GA1Ud
    EwEB/wQFMAMBAf8wCgYIKoZIzj0EAwIDSAAwRQIgBsRwbwJyFF74N2PVzc7R6nPE
    7Ot8gGj6Vg5dJbFseioCIQD2m1DYj2F3UAf9FV9l4EXz1qWn7yLpso9NRSQM4Iub
    fw==
    -----END CERTIFICATE-----
  key.pem: |
    -----BEGIN EC PRIVATE KEY-----
    MHcCAQEEIMwe5F1H9vpIY3LSBk+g6QrSMsCgNQWyWJG1YmnTnhWwoAoGCCqGSM49
    AwEHoUQDQgAE5Aamr37PUJ2+YE+Hp+xXAzRkSf5L7VzMwLoBXr1NeK7j9VSNfCsw
    lq2UvEsmvqVsIIjrVLXZD9IdPymcgIZEdg==
    -----END EC PRIVATE KEY-----
