tests: # SEE README.MD for detailed information on each configuration paramter
  vaults: # Tests vault creation and deletion operations, see README.MD for details on config paramaters
    enabled: true
    count:
      - 50
      - 100
    prefix: vault-test
    clean_up: false # SEE README.MD
  e2e: # Tests full lifecycle (create vault -> load attributes -> delete attributes -> delete vault), see README.MD for details on config paramaters
    enabled: true
    count:
      - 50
      - 100
    prefix: e2e-test
    clean_up: false
  attributes: # Tests standalone attribute operations, see README.MD for details on config paramaters
    enabled: true
    count:
      - 50
      - 100
    vault_count: 10
    prefix: attr-test
    clean_up: false
  tokenizer: # Tests tokenize only, see README.MD for details on config paramaters
    enabled: true
    count:
      - 50
      - 100
    vault_count: 10
    prefix: tokenizer-test
    realm: data-loader # IMPORTANT: This needs to match the realm you are running your tests
    clean_up: false
    value_min: 4
    value_max: 32
    tokens_per_job:
      - 1
      - 2
    token_type:  # Can be EPHEMERAL or PERSISTENT
      - EPHEMERAL
      - PERSISTENT
  tokenizer_translate_e2e: # Tests tokenize + translate e2e time, see README.MD for details on config paramaters
    enabled: true
    count:
      - 50
      - 100
    vault_count: 10
    prefix: tokenizer-e2e-test
    realm: data-loader # IMPORTANT: This needs to match the realm you are running your tests
    clean_up: false
    value_min: 4
    value_max: 32
    tokens_per_job:
      - 1
      - 2
    token_type:  # Can be EPHEMERAL or PERSISTENT
      - EPHEMERAL
      - PERSISTENT
concurrency: # SEE README.MD
  - 16
  - 32
  - 64
log_level: trace  # Available levels: trace, debug, info, error

#reports:               # optional define custom path for test reports. Default is ./reports/manetu-perf-results-<hh-mm-MM-dd-yyyy>.[csv|json]
#  csv: "reports.csv"   # Path for CSV report output
#  json: "reports.json" # Path for JSON report output