tests:
  vaults:
    # Tests vault creation and deletion operations
    enabled: true
    count:
      - 50  # Supports supplying multiple values for count
      - 100 # Test will run multiple times for each value of count supplied
    prefix: vault-test
    clean_up: false # ONLY set to true if previous test run ended prematurely and wasn't able to clean up data. See README.MD for more details.
  e2e:
    # Tests full lifecycle (create vault -> load attributes -> delete attributes -> delete vault)
    enabled: true
    count:
      - 50  # Supports supplying multiple values for count
      - 100 # Test will run multiple times for each value of count supplied
    prefix: e2e-test
    clean_up: false # ONLY set to true if previous test run ended prematurely and wasn't able to clean up data. See README.MD for more details.
  attributes:
    # Tests standalone attribute operations
    enabled: true
    count:
      - 50  # Supports supplying multiple values for count
      - 100 # Test will run multiple times for each value of count supplied
    vault_count: 10  # Number of vaults to create for attribute operations
    prefix: attr-test
    clean_up: false # ONLY set to true if previous test run ended prematurely and wasn't able to clean up data. See README.MD for more details.
  tokenizer:
    # Tests tokenize only
    enabled: true
    count:
      - 50   # Supports supplying multiple values for count
      - 100 # Test will run multiple times for each value of count supplied
    vault_count: 10
    prefix: tokenizer-test
    realm: data-loader # IMPORTANT: This needs to match the realm you are running your tests
    clean_up: false
    value_min: 4
    value_max: 32
    tokens_per_job:
      - 1 # Supports supplying multiple values for tokens_per_job
      - 2 # Test will run multiple times for each value of tokens_per_job supplied
    token_type:
      - EPHEMERAL  # Supports supplying both, this will run the test twice, once for each token type
      - PERSISTENT # Can be EPHEMERAL or PERSISTENT
  tokenizer_translate_e2e:
    # Tests tokenize + translate e2e time
    enabled: true
    count:
      - 50   # Supports supplying multiple values for count
      - 100 # Test will run multiple times for each value of count supplied
    vault_count: 10
    prefix: tokenizer-e2e-test
    realm: data-loader # IMPORTANT: This needs to match the realm you are running your tests
    clean_up: false
    value_min: 4
    value_max: 32
    tokens_per_job:
      - 1  # Supports supplying multiple values for tokens_per_job
      - 2  # Test will run multiple times for each value of tokens_per_job supplied
    token_type:
      - EPHEMERAL  # Supports supplying both, this will run the test twice, once for each token type
      - PERSISTENT # Can be EPHEMERAL or PERSISTENT
concurrency:
  # note: count values for all sections (especially vault_count for attributes)
  # should be greater than concurrency values for accurate performance measurements
  # e.g: To fire 64 concurrent attribute operation requests, there needs to be 64
  # or more vaults (vault_count>64)
  - 16
  - 32
  - 64
log_level: trace  # Available levels: trace, debug, info, error

#reports:               # optional define custom path for test reports. Default is ./reports/manetu-perf-results-<hh-mm-MM-dd-yyyy>.[csv|json]
#  csv: "reports.csv"   # Path for CSV report output
#  json: "reports.json" # Path for JSON report output